### ISSUE TITLE
Python code to write the midi file ?

### ISSUE THREAD

**Issue by SutirthaChakraborty** [timwedde/py_midicsv#10]
What is the python code to export the csv_string to a csv file ? 

`csv_string = pm.midi_to_csv(path)`

Thanks,

**Comment by timwedde** [comment]
This is just a regular Python string. As such you can write it out like you would any other string:
```python
csv_string = "some csv data"

with open("out.csv", "w") as f:
    f.write(csv_string)
```

**Comment by SutirthaChakraborty** [comment]
I think that gives an error. But I solve it like this: 
`csv_string1 = pm.midi_to_csv(path1)
content = [x.strip().split(', ') for x in csv_string] 
data=pd.DataFrame(content)
data`

**Comment by timwedde** [comment]
Ah, my bad. It's been a while since I came back to this. It actually returns a list of strings, so you should be able to:
```python
csv_string = ["some\n", "csv\n", "data\n"]

with open("out.csv", "w") as f:
    f.writelines(csv_string)
```

Alternatively you can join the strings together into one big string:
```python
csv_string = ["some\n", "csv\n", "data\n"]

joined_string = "".join(csv_string)
```

**Comment by timwedde** [comment]
Since this is resolved I am closing this issue.

**Comment by SutirthaChakraborty** [comment]
Thanks, Just to ask you, when we convert into CSV,  the timestamp which we get, is that in milliseconds?
I mean how do I convert that timestamp into seconds? if I need to chop of sections from the csv?

**Comment by timwedde** [comment]
Some documentation is available [here](https://github.com/timwedde/py_midicsv/blob/master/doc/file-format.md).
The `Time` field refers to the midi clock signal. This is a bit tricky, because this can change. For example, if a song has a tempo change in the middle, the midi clock will start ticking at a different speed after that tempo change event.

As such you can not assume that the Time field can be interpreted as any conventional time unit as it is. It needs to be in the context of either the start of the file (which defines the pulses per quarter note) or a tempo change event that occured before the line you're looking at.

The formula for converting to milliseconds is `60000 / (BPM * PPQ)`. The two variables can be extracted from the MIDI file itself (though keep in mind that songs with tempo changes will need to apply this formula section by section). This formula gives you the amount of milliseconds that 1 MIDI tick takes.

Some more info can be found [here](https://stackoverflow.com/a/54754549).

**Comment by SutirthaChakraborty** [comment]
Thank you so much for the detailed explanation. Just to confirm, the time in seconds if I have the time like this- 
![image](https://user-images.githubusercontent.com/47362033/107299818-2dab1400-6a70-11eb-9160-4434aa56fa6d.png)

timestamp = 36960
BPM = 100
time in seconds =???

**Comment by timwedde** [comment]
You also need the PPQ (pulses per quarter note), as I mentioned above.
Assuming the default value of 960, this would allow you to calculate the length as follows:
```
36960 * (60000 / (100 * 960))
```

Which works out to 23.1 seconds, since the output of that formula is in milliseconds. Depending on the PPQ, this duration can change, naturally, so be sure to check what the actual value is in your MIDI file.
