### ISSUE TITLE
Track meta-events—ignored?

### ISSUE THREAD

**Issue by TWCCarlson** [timwedde/py_midicsv#15]
I've used your library to successfully convert a midi file (or twelve) into .csv, with the exact same results as the unix midicsv functions. I was hoping your library would also handle meta-events for simplicity and convenience. The simplicity and convenience factors may be fairly limited for general use, so I will not be surprised if you feel it unnecessary.

My midi files definitely contain the information—Musescore 4 identifies the instruments correctly from the same file. Ideally I would like to have it available to any parsing scripts I pass over the .csv.

Is this a feature that is out of scope for the library?

**Comment by TWCCarlson** [comment]
Actually it seems that these midi files are somehow non-standard. I wonder why. Here's some files if you're curious: https://drive.google.com/drive/folders/1imRDwsKzwfOma4W_B0YO_jZSxdqNYRxL

The library certainly works for other songs.

**Comment by timwedde** [comment]
Meta events should be supported, that's certainly within the scope of this library.
I did run through the 759 files you helpfully provided, but it appears that they do not contain any metadata, at least not in the usual format, like you also noted in your second comment.

With the latest version of the library that I just released, I'm able to convert all of these files except for three of them back and forth losslessly. The three non-identical files are ones that contain test silence or the like and end with an additional zero byte, likely because the original one omitted it, but it's required by the spec, which this library adheres to when writing.

As of now, everything seems to be working as it should, far as I can tell. Should this change, don't hesitate to let me know, either by reopening this issue or creating a new one. I'll be happy to look into it, time permitting.

**Comment by TWCCarlson** [comment]
My erroneous assumption arises from sticking those same midis into Musescore which correctly identifies the instruments at play in the midis. I assumed the metadata must be present, and I'm not sure where it is if it's not showing up in the .csv, but your library certainly works flawlessly right now.

**Comment by timwedde** [comment]
I suspect MuseScore may be inferring parts of that information from program change events or the like, so that may explain -at least in part- why the correct instruments show up there despite no actual metadata being present.
