### ISSUE TITLE
Ignore commas at end of line

### ISSUE THREAD

**Issue by michgz** [timwedde/py_midicsv#17]
This is such a fantastic way to edit MIDI files - just change into text, edit, then change back again! Simple, but brilliant - glad to have found this project.

The issue I'm coming across is that for CSV files with mixed row lengths (such as these), Microsoft Excel will add extraneous commas to  the ends of rows and they cause csvmidipy to fail. They can be removed fairly easily with Python script / RE / etc., but if the library could just ignore them it would be 1 fewer steps.

**Comment by timwedde** [comment]
Yeah, that's a good idea. Alas, it is a little complicated because it's not really possible to tell apart an extra trailing comma and a deliberately empty last column. The intent is not encoded in this file format, so we have to take a guess. This makes it much harder to handle this use case properly. Yet again, Microsoft makes things worse for everyone.

I've just pushed a 'fix' for this which makes the parsing a little more strict in that it will only consider values it actually cares about, instead of 'whatever is the rest of this parsed line'. This should prevent issues with trailing commas (at least in my testing) but please note that there is a specific failure case for SysEx events: Since SysEx data can be arbitrary, it's impossible for us to know whether a trailing comma should be discarded as a null byte or whether the null byte is actually part of the SysEx data (for example it might contain a null-terminated string). As such, if you use this library on MIDI files that contain SysEx data and rely on that data being intact after a conversion to CSV and back, do note that you still have to care about trailing commas. For all other events, however, this should now be taken into account.

I would also recommend maybe editing these CSV files in some other editor that doesn't deliberately mess up your data.

I'm releasing `4.1.0` at the moment, please give it a try and let me know whether this new behavior works better for you :)

**Comment by michgz** [comment]
Thanks, 4.1.0 completely solves the problem in my use-case. 

(In fairness to Microsoft, LibreOffice behaves the same, i.e. adds the extra commas).

Will close..
