### ISSUE TITLE
Don't work

### ISSUE THREAD

**Issue by npeeth** [timwedde/py_midicsv#6]
in https://pypi.org/project/py-midicsv/#description

we have

```
import py_midicsv

# Load the MIDI file and parse it into CSV format
csv_string = py_midicsv.midi_to_csv("example.mid")

# Parse the CSV output of the previous command back into a MIDI file
midi_object = py_midicsv.csv_to_midi(csv_string)

# Save the parsed MIDI file to disk
with open("example_converted.mid", "wb") as output_file:
    midi_writer = py_midicsv.FileWriter(output_file)
    midi_writer.write(midi_object)
```

in https://github.com/timwedde/py_midicsv

we have

```
import py_midicsv as pm

# Load the MIDI file and parse it into CSV format
csv_string = pm.midi_to_csv("example.mid")

# Parse the CSV output of the previous command back into a MIDI file
midi_object = pm.csv_to_midi(csv_string)

# Save the parsed MIDI file to disk
with open("example_converted.mid", "wb") as output_file:
    midi_writer = pm.FileWriter(output_file)
    midi_writer.write(midi_object)
```

but none of them work or i did something wrong

```
Traceback (most recent call last):
  File "C:/Users/felipe/PycharmProjects/2020/PORRA.py", line 9, in <module>
    midi_writer.write(midi_object)
NameError: name 'midi_object' is not defined
```

**Comment by kevinsolie** [comment]
Make sure you have example.mid file in the right place

**Comment by timwedde** [comment]
It looks like you failed to initialize the `midi_object` variable. Please provide some more information:
What version of Python are you using?
What version of `py_midicsv` are you using?
Which operating system are you on?

It would also be beneficial if you could post the actual code from your `PORRA.py` file as it is likely that there is some mistake in there, not in the example.
Please note that the example is simply a structural one, it showcases how the basic process works, it is not intended to be pasted into an arbitrary file and run from an arbitrary location.

Please also note that both of the examples you posted are identical, there is no difference between them. This is because the description on PyPi is generated from the actual README in this repository, hence they will always be the same.

**Comment by timwedde** [comment]
Closing this due to a lack of response.
